# najbardziej podstawowa konfiguracja radvd
# rozgłasza wszystkie prefiksy interfejsu eth1
#
# zduplikuj blok "interface" zmieniając nazwę interfejsu,
# by rozgłaszać możliwości routingu również na innych interfejsach

interface eth1 {
  AdvSendAdvert on;
  prefix ::/64 {

  };
};
